[package]
name = "smalloc"
license = "MIT"
description = "A small memory allocator for Solana programs"
version = "0.1.1"
edition = "2021"
repository = "https://github.com/oxfeeefeee/smalloc"


[features]
default = []
dynamic_start = []

[dependencies]
solana-program = "1.14.5"
